FROM rust:1.38

RUN rustup default nightly-2019-08-28 && \
    cargo --version && \
    apt-get update && \
    apt-get install -y curl build-essential git openssl pkg-config libssl-dev libgmp3-dev

WORKDIR /tss

COPY ./multi-party-ecdsa/Cargo.lock ./multi-party-ecdsa/Cargo.toml /tss/
COPY ./multi-party-ecdsa/src/lib.rs /tss/src/lib.rs

# Download all dependencies
RUN cargo fetch

# Build dependencies
RUN cargo build --release || true

COPY ./multi-party-ecdsa /tss/

# Build final executables
RUN cargo build --release

CMD echo Done
